### PR TITLE
Improve compile time and small changes

### PR DESCRIPTION
**Pull request by jakobkmar**
- upgraded Kotlin version
- upgraded Gradle version (better compile time and shadow plugin with new fixes)
- use the global CORES constant when running the multithreaded solution

Also, I wanted to ask why you are using
`implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1-native-mt")`
as the coroutines dependency (defined for `commonMain`)?

@fvbakel due to the upgraded Gradle version, you have to publish a new version of you custom Docker image if this PR is merged.

### CODE REVIEW

**Comment by fvbakel** [comment]
@bluefireoly 

Great ideas, I have no inside knowledge of Kotlin to have any opinion on it. However, the change in the dockerfiles depends a bit on the discussion in [https://github.com/PlummersSoftwareLLC/Primes/pull/309](https://github.com/PlummersSoftwareLLC/Primes/pull/309)

**Comment by Theaninova** [comment]
> Also, I wanted to ask why you are using
> `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1-native-mt")`
> as the coroutines dependency (defined for `commonMain`)?

The `native-mt` is supposed to support multithreading, look [here](https://kotlinlang.org/docs/mobile/concurrency-and-coroutines.html#multithreaded-coroutines) for a more detailed explanation.

**Comment by jakobkmar** [comment]
> However, the change in the dockerfiles depends a bit on the discussion

Yes, but we could merge this and then change the Dockerfile later on if it is necessary.

**Comment by fvbakel** [comment]
@bluefireoly No problem to update the Docker file after the merge of this PR. Let me know if you need my help to do that.

**Comment by Theaninova** [comment]
Nice, looking good to me, sorry about the holdup, I'm used to people adding a `Please Review` once they are ready to merge :)

**Comment by jakobkmar** [comment]
> sorry about the holdup, I'm used to people adding a Please Review once they are ready to merge :)

my fault, I forgot it this time :)

**Pull request merged**
